name: Docker image build

on:
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: build the image
        run: |
          docker buildx build \
            --tag realdeadbeef/ipmi-bot:${{ github.event.release.tag_name }} \
            --platform linux/amd64,linux/arm/v7,linux/arm64 . 
          docker buildx build \
            --tag realdeadbeef/ipmi-bot:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: push the image
        run: |
          docker buildx build --push \
            --tag realdeadbeef/ipmi-bot:${{ github.event.release.tag_name }} \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
          docker buildx build --push \
            --tag realdeadbeef/ipmi-bot:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
